name: gmwc

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN || github.token }}

      - name: Sync with upstream
        if: github.repository != 'Tsuk1ko/gmwc'
        continue-on-error: true
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.ACCESS_TOKEN || github.token }}
          upstream_sync_repo: Tsuk1ko/gmwc
          upstream_sync_branch: main

      - name: Keep alive
        if: github.repository == 'Tsuk1ko/gmwc'
        uses: gautamkrishnar/keepalive-workflow@master

      - name: Cache
        uses: actions/cache@v3
        with:
          path: cache
          key: gc-cache-v3-${{ github.run_id }}
          restore-keys: |
            gc-cache-v3-

      - name: Install dependencies
        run: yarn install --production --frozen-lockfile

      - name: Checkin
        env:
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
        run: yarn start
